[project]
name = "jobcopilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Veaceslav BEZUŞCO", email = "veaceslav.bezusco@orange.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langgraph>=1.2.11",
    "openai>=3.10.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
jobcopilot = "jobcopilot:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
